feat: PROJ-152 : 앨범 페이지 마크업 및 스타일링, 보기 아이콘 기능 추가
hanium-4ward/Diarist pull request #53
Opened 2024-07-08 10:45 UTC by whddbsl

## Jira 티켓

[PROJ-32](https://hanium.atlassian.net/browse/PROJ-32)
[PROJ-149](https://hanium.atlassian.net/browse/PROJ-149)
[PROJ-152](https://hanium.atlassian.net/browse/PROJ-152)

## 제목

앨범 페이지 기본 마크업 및 스타일링, 보기 아이콘 기능 추가

## 작업유형

- [ ] 버그픽스
- [x] 기능 추가/수정
- [ ] 코드 스타일 갱신
- [x] 마크업 완성
- [x] 스타일링 완성
- [ ] 리팩터링(Refactoring)
- [ ] 문서 추가/수정
- [ ] 기타:

## 변경 전

- 앨범 페이지 마크업 및 스타일링 미구현
- 썸네일 보기 형식, 앨범 보기 형식 토글 미구현

## 변경 후

앨범 페이지 마크업 및 스타일링 구현
썸네일 보기 형식, 앨범 보기 형식 토글 구현
- 토글 선택에 따라 페이지 레이아웃 변경

2024-07-08 13:07 UTC, JMboy713 requested changes
package-lock.json 파일 경로가 이상한데 확인부탁드립니다!

2024-07-08 13:07 UTC, JMboy713 commented on package-lock.json
package-lock.json 파일 경로가 이상한데 확인부탁드립니다!

2024-07-08 13:11 UTC, whddbsl commented on package-lock.json
오 굳 수정했습니다

2024-07-08 13:39 UTC, JMboy713 approved these changes
LGTM😊! 고생하셨습니다!

2024-07-08 15:35 UTC, kkk1k approved these changes
LGTM~
다음에는 구현부분 캡처해서 부탁드립니다~

2024-07-09 05:29 UTC, minsuhaha approved these changes
LGTM~ 고생하셨습니다

2024-07-10 05:35 UTC, merged